server:
  port: 21002
spring:
  application:
    name: springboot-redis-cluster
  redis:
    database: 13
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    cluster:
      nodes:
        - 192.168.253.130:7000
        - 192.168.253.130:7001
        - 192.168.253.130:7002
        - 192.168.253.130:7003
        - 192.168.253.130:7004
        - 192.168.253.130:7005
      # 获取失败 最大重定向次数
      max-redirects: 3
